version: "3.9"

services:
  db: 
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: junglebook
      POSTGRES_PASSWORD: baloo
      POSTGRES_DB: eddycurrent
